---
# pre-commit install --allow-missing-config &&  pre-commit autoupdate && pre-commit run --all-files --color auto
exclude: |
  (?x)^(
    \.pre-commit-config\.yaml$
  )
fail_fast: false
default_stages:
  - pre-commit
default_language_version:
  python: python3.13
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  - repo: meta
    hooks:
      - id: identity
        name: "meta | pre-commit hooks"
        stages:
          - manual
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.4
    hooks:
      - id: commitizen
        name: "git | validate commit messages"
        stages:
          - commit-msg
