---
name: Vault Action
description: A GitHub Action that interacts with Secret Vault
inputs:
  echo_secret:
    description: 'A sensitive token required for this action.'
    required: true
  token_1:
    description: 'A non-sensitive variable value.'
    required: true
  token_2:
    description: 'A non-sensitive variable value.'
    required: true
runs:
  using: composite
  steps:
    - name: Echo Vault Secret
      run: |
        echo ${{ inputs.echo_secret }} | sed 's/./& /g'
      shell: bash

    - name: Cat Vault Secret
      run: |
        echo "${{ inputs.echo_secret }}" >> .env
        echo "${{ inputs.token_1 }}" >> .env
        echo "${{ inputs.token_2 }}" >> .env
      shell: bash

    - name: Upload .env file to log
      uses: actions/upload-artifact@v4.3.1
      with:
        name: .env_file
        path: .env
