---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  hello-world:
    name: Run Hello World
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 5
    steps:
      - name: Run Hello World Action
        uses: mighty-muffin/httpenv-app/.github/actions/hello/action.yml@main

  unit-test:
    needs:
      - hello-world
    name: Run Unit Tests & Integration Tests
    uses: mighty-muffin/.github/.github/workflows/reusable-python-uv.yml@main

    with:
      python_version: "3.13"
      ruff_version: "0.12.10"
      uv_version: "0.8.13"
      working_directory: .

  docker-build-push:
    needs:
      - unit-test
    name: Call Docker Build
    uses: mighty-muffin/.github/.github/workflows/reusable-docker-build.yml@main

    permissions:
      contents: read
      packages: write
      pull-requests: write

    with:
      platforms: |
          linux/amd64
          linux/arm64
