---
name: CI - Repository

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-repo-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  security-events: write
  contents: read

jobs:

  pinned-actions:
    name: Check Repo Workflow
    uses: mighty-muffin/.github/.github/workflows/reusable-ensure-pin-actions.yml@main
